"""
Custom Computation Node
Executes user-defined Python functions on tensors.
"""

from inspect import cleandoc
from custom_nodes.utils.visnode_base import RoboticsNodeBase
from custom_nodes.utils.node_colors import get_node_colors
from custom_nodes.utils.dnne_decorator import dnne_node
from custom_nodes.utils.script_loader import load_custom_script

@dnne_node(is_virtual=False)
class CustomComputationNode(RoboticsNodeBase):
    """Custom Computation Node
    Executes user-defined Python functions on tensors."""
    
    DESCRIPTION = cleandoc(__doc__)
    COLOR = get_node_colors("utility")["color"]
    BGCOLOR = get_node_colors("utility")["bgcolor"]
    CATEGORY = "utility"

    @classmethod
    def INPUT_TYPES(cls):
        inputs = {
            "required": {
                "input": ("*TENSOR", {
                    "tooltip": "Input tensor to process with custom function"
                }),
                "src_path": ("STRING", {
                    "default": "",
                    "multiline": False,
                    "tooltip": "Path to Python file containing compute(input: Tensor) -> Tensor function"
                }),
                "config": ("STRING", {
                    "default": "{}",
                    "multiline": False,
                    "tooltip": "Python dict for configuration, e.g. {\"DEBUG\": True, \"scale\": 2.0}"
                }),
            }
        }
        
        # Update return type based on script
        cls._update_return_type(inputs)
        
        return inputs
    
    @classmethod
    def _update_return_type(cls, inputs):
        """Update RETURN_TYPES based on loaded script."""
        src_path = inputs["required"]["src_path"][1]["default"].strip()
        
        if not src_path:
            # No script specified yet - use wildcard
            cls.    OUTPUT_DICT = {
        0: {"type": "*", "name": "output"}
    }
    # RETURN_TYPES and RETURN_NAMES auto-generated by OutputDictMixin
            return
        
        try:
            # Load script and get output type
            module = load_custom_script(src_path)
            cls.RETURN_TYPES = (module.get_output_type(),)
        except Exception:
            # Script not available yet - use wildcard
            cls.RETURN_TYPES = ("*",)
    FUNCTION = None  # DNNE nodes don't execute in UI, only export
    
    @classmethod
    def VALIDATE_INPUTS(cls, **kwargs):
        """Validate that src_path is provided and script has required functions."""
        # src_path is required - fail if not provided
        if "src_path" not in kwargs:
            return "src_path parameter is required"
        src_path = kwargs["src_path"].strip()
        if not src_path:
            return "src_path is required - must point to a Python file with required functions"
        
        # Try to load and validate the script
        try:
            module = load_custom_script(src_path)
            # Script loaded successfully with all required functions
            return True
        except FileNotFoundError as e:
            return f"Script file not found: {src_path}"
        except AttributeError as e:
            return str(e)  # Will contain info about missing function
        except Exception as e:
            return f"Failed to load script: {str(e)}"

# Node registration
NODE_CLASS_MAPPINGS = {
    "CustomComputation": CustomComputationNode
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "CustomComputation": "Custom Computation"
}