"""
SGD Optimizer Node
Stochastic Gradient Descent optimizer that performs training steps.
Combines optimizer creation with backpropagation and parameter updates.
"""

from inspect import cleandoc
from custom_nodes.utils.visnode_base import RoboticsNodeBase
from custom_nodes.utils.node_colors import get_node_colors
from custom_nodes.utils.dnne_decorator import dnne_node


@dnne_node(is_virtual=False)
class SGDOptimizerNode(RoboticsNodeBase):
    """SGD Optimizer Node
    Stochastic Gradient Descent optimizer that performs training steps.
    Combines optimizer creation with backpropagation and parameter updates."""
    
    DESCRIPTION = cleandoc(__doc__)
    COLOR = get_node_colors("training")["color"]
    BGCOLOR = get_node_colors("training")["bgcolor"]

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "model": ("*MODEL_OBJ", {
                    "virtual": True,
                    "tooltip": "Neural network model to optimize. Must have parameters to train."
                }),
                "loss": ("*LOSS_SCALAR", {
                    "tooltip": "Loss scalar to backpropagate. Triggers training step when received."
                }),
                "learning_rate": ("FLOAT", {
                    "default": 0.01,
                    "min": 0.0,
                    "max": 1.0,
                    "step": 0.0001,
                    "tooltip": "Learning rate controls step size. Start with 0.01 or 0.001, adjust based on loss curve. Set to 0 to freeze weights."
                }),
                "momentum": ("FLOAT", {
                    "default": 0.9,
                    "min": 0.0,
                    "max": 0.999,
                    "step": 0.001,
                    "tooltip": "Momentum factor accelerates SGD in relevant direction. 0.9 is a good default."
                }),
                "weight_decay": ("FLOAT", {
                    "default": 0.0,
                    "min": 0.0,
                    "max": 0.1,
                    "step": 0.0001,
                    "tooltip": "L2 penalty (regularization). Helps prevent overfitting. Try 0.0001 to 0.001."
                }),
                "batch_size": ("INT", {
                    "default": 1,
                    "min": 1,
                    "max": 128,
                    "step": 1,
                    "tooltip": "Gradient accumulation batch size. Accumulates gradients over N steps before updating weights. Default 1 = no accumulation."
                }),
                "enable_bootstrap": ("BOOLEAN", {
                    "default": True,
                    "tooltip": "Send initial step_complete signal to start training loop. Disable if manually controlling flow."
                })
            }
        }

    OUTPUT_DICT = {
        0: {"type": "TRAIN_STEP_TRIGGER", "name": "step_complete"}
    }
    # RETURN_TYPES and RETURN_NAMES auto-generated by OutputDictMixin
    FUNCTION = None  # DNNE nodes don't execute in UI, only export
    CATEGORY = "ml"

# Node registration
NODE_CLASS_MAPPINGS = {
    "SGDOptimizer": SGDOptimizerNode
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "SGDOptimizer": "SGD Optimizer"
}