"""
Split Node for tensor splitting with configurable slicing
Splits a single tensor input into up to 4 outputs based on indices or sizes
"""

from inspect import cleandoc
from custom_nodes.utils.visnode_base import RoboticsNodeBase
from custom_nodes.utils.node_colors import get_node_colors
from custom_nodes.utils.dnne_decorator import dnne_node

@dnne_node(is_virtual=False)
class SplitNode(RoboticsNodeBase):
    """
    Split Node for tensor splitting
    Splits a single tensor input into up to 4 outputs along a specified dimension
    
    Modes:
    - by index: Split at specific indices (e.g., "10,20,30" splits at positions 10, 20, 30)
    - by size: Split into chunks of specific sizes (e.g., "10,10,10,10" creates 4 chunks of size 10)
    - by name: Split using semantic names from upstream schema (e.g., "joint_positions,joint_velocities")
    
    The number of outputs depends on the split_pos specification:
    - For "by index" with N indices: Creates N+1 outputs
    - For "by size" with N non-zero sizes: Creates N outputs
    - For "by name" with N names: Creates N outputs
    """
    
    CATEGORY = "utility"
    COLOR = get_node_colors("utility")["color"]
    BGCOLOR = get_node_colors("utility")["bgcolor"]
    
    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "input": ("*TENSOR", {"tooltip": "Input tensor to split"}),
                "dimension": ("INT", {
                    "default": 0,
                    "min": 0,
                    "max": 3,
                    "tooltip": "Dimension along which to split the tensor (0=batch, 1=channels, etc.)"
                }),
                "split_mode": (["by index", "by size", "by name"], {
                    "default": "by index",
                    "tooltip": "How to interpret split_pos: indices, sizes, or semantic names from schema"
                }),
                "split_pos": ("STRING", {
                    "default": "10,20,30",
                    "tooltip": "Comma-separated values. 'by index': split points. 'by size': chunk sizes. 'by name': semantic names from schema."
                }),
            }
        }

    OUTPUT_DICT = {
        0: {"type": "*TENSOR", "name": "output_a"},
        1: {"type": "*TENSOR", "name": "output_b"},
        2: {"type": "*TENSOR", "name": "output_c"},
        3: {"type": "*TENSOR", "name": "output_d"}
    }
    # RETURN_TYPES and RETURN_NAMES auto-generated by OutputDictMixin
    FUNCTION = None  # DNNE nodes don't execute in UI, only export
    DESCRIPTION = cleandoc(__doc__)

# Node registration
NODE_CLASS_MAPPINGS = {
    "Split": SplitNode
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "Split": "Split"
}