#!/usr/bin/env python3
"""
Generated by DNNE - Main Entry Point
Metadata: {METADATA}
"""

import sys
import os
import argparse
from pathlib import Path
import warnings

# Suppress common warnings that clutter the output
warnings.filterwarnings('ignore', category=DeprecationWarning)
warnings.filterwarnings('ignore', category=FutureWarning)
warnings.filterwarnings('ignore', message='.*FBX library failed to load.*')
warnings.filterwarnings('ignore', message='.*invalid escape sequence.*')
warnings.filterwarnings('ignore', message='.*Box bound precision lowered.*')
warnings.filterwarnings('ignore', message='.*pkg_resources is deprecated.*')
warnings.filterwarnings('ignore', message='.*torch.cuda.amp.GradScaler.*is deprecated.*')
warnings.filterwarnings('ignore', message='.*torch.cuda.amp.autocast.*is deprecated.*')
warnings.filterwarnings('ignore', message='.*Using or importing the ABCs from.*')
warnings.filterwarnings('ignore', message='.*np.int.*is a deprecated alias.*')
warnings.filterwarnings('ignore', message='.*declare_namespace.*')
warnings.filterwarnings('ignore', message='.*Future Hydra versions will no longer change working directory.*')

# Add current directory to Python path for imports
sys.path.insert(0, str(Path(__file__).parent))

# Configure paths using DNNE configuration system
from framework import dnne_config

# Get paths from configuration
isaac_gym_path = str(dnne_config.get_isaac_gym_path())
isaac_gym_envs_path = str(dnne_config.get_isaac_gym_envs_path())
linux_support_path = str(dnne_config.get_linux_support_path())
rl_games_path = str(dnne_config.get_rl_games_path())

# Add paths to Python path
sys.path.append(os.path.join(isaac_gym_path, "python"))
sys.path.append(linux_support_path)
sys.path.append(isaac_gym_envs_path)
sys.path.append(rl_games_path)

print(f"Using paths from dnne_config: isaac_gym={{isaac_gym_path}}")

# Isaac Gym must be always be imported before pytorch to avoid import order issues
try:
    import isaacgym
except ImportError:
    print("⚠️  Isaac Gym not found. Simulation features will be disabled.")

import asyncio
import logging

{NODE_IMPORTS_SECTION}
from framework import GraphRunner
from framework.override_parser import parse_override_args
# NOTE: Removed 'from nodes import *' - caused double Isaac Gym initialization
# All required nodes are imported explicitly above

def configure_logging(verbose=None, debug=None):
    """Configure logging based on verbosity flags with optional subsystem control"""
    # Create a shared console handler
    console_handler = logging.StreamHandler()
    
    # Determine format based on verbosity
    if debug and debug != 'all':
        format_str = '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    elif verbose and verbose != 'all':
        format_str = '%(asctime)s - %(name)s - %(message)s'
    else:
        format_str = '%(asctime)s - %(name)s - %(message)s'
    
    formatter = logging.Formatter(format_str)
    console_handler.setFormatter(formatter)
    
    # Handle 'all' modes using basicConfig
    if debug == 'all':
        logging.basicConfig(
            level=logging.DEBUG,
            format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
            force=True
        )
        return
    elif verbose == 'all':
        logging.basicConfig(
            level=logging.INFO,
            format='%(asctime)s - %(name)s - %(message)s',
            force=True
        )
        return
    
    # For subsystem-specific logging, configure root logger minimally
    logging.basicConfig(level=logging.WARNING, force=True)
    
    # Configure specific subsystem loggers
    if debug and debug != 'all':
        # Set specific subsystems to DEBUG
        console_handler.setLevel(logging.DEBUG)
        for subsystem in debug.split(','):
            subsystem = subsystem.strip()
            # Check if subsystem is a node ID (numeric)
            if subsystem.isdigit():
                logger_name = f"dnne.node.{{subsystem}}"
            else:
                logger_name = f"dnne.{{subsystem}}"
            logger = logging.getLogger(logger_name)
            logger.setLevel(logging.DEBUG)
            logger.addHandler(console_handler)
            logger.propagate = False  # Prevent duplicate output
            # Defensive measure against external configs
            if hasattr(logger, 'disabled'):
                logger.disabled = False
    
    if verbose and verbose != 'all':
        # Set specific subsystems to INFO
        if not debug:  # Only create handler if not already created
            console_handler.setLevel(logging.INFO)
        for subsystem in verbose.split(','):
            subsystem = subsystem.strip()
            # Check if subsystem is a node ID (numeric)
            if subsystem.isdigit():
                logger_name = f"dnne.node.{{subsystem}}"
            else:
                logger_name = f"dnne.{{subsystem}}"
            logger = logging.getLogger(logger_name)
            # Only configure if not already set to DEBUG
            if not (debug and subsystem in debug):
                logger.setLevel(logging.INFO)
                logger.addHandler(console_handler)
                logger.propagate = False
                if hasattr(logger, 'disabled'):
                    logger.disabled = False

async def main():
    """Main execution function"""
    # Parse command line arguments
    parser = argparse.ArgumentParser(description='DNNE Generated Training')
    parser.add_argument('--verbose', '-v', nargs='?', const='all', default=None,
                       help='Enable verbose logging (INFO level). Optional: comma-separated subsystems or node IDs (e.g., "mnist,42,queue" or "55")')
    parser.add_argument('--debug', '-d', nargs='?', const='all', default=None,
                       help='Enable debug logging (DEBUG level). Optional: comma-separated subsystems or node IDs (e.g., "yield,66,ppo" or "42")')
    parser.add_argument('--save-checkpoint', action='store_true',
                       help='Enable checkpoint saving')
    parser.add_argument('--out-dir', type=str, default='runs/singles',
                       help='Output directory for checkpoints and other outputs (default: runs/singles)')
    parser.add_argument('--load-checkpoint', type=str,
                       help='Directory to load checkpoints from (expects node_<id> subdirectories)')
    parser.add_argument('--timeout', type=str,
                       help='Training duration (e.g., 5, 30s, 5m, 1h30m)')
    parser.add_argument('--visual', action='store_true',
                       help='Enable visual mode (overrides headless setting)')
    parser.add_argument('--headless', action='store_true',
                       help='Force headless mode (default)')
    parser.add_argument('--inference', action='store_true',
                       help='Run in inference mode (no training, no gradients)')
    parser.add_argument('--dnne-profiling', action='store_true',
                       help='Enable profiling for C++ operations (Isaac Gym)')
    parser.add_argument('--epochs', type=str, default=None,
                       help='Override max epochs for EpochTracker nodes (e.g., --epochs 10 or --epochs 55:10,56:20)')
    parser.add_argument('--max-iterations', type=str, default=None,
                       help='Override max iterations for PPOAgent nodes (e.g., --max-iterations 1000 or --max-iterations 66:5000,67:10000)')
    parser.add_argument('--learning-rate', type=str, default=None,
                       help='Override learning rate for SGDOptimizer nodes (e.g., --learning-rate 0.01 or --learning-rate 68:0.001,69:0.01)')
    parser.add_argument('--batch-size', type=str, default=None,
                       help='Override batch size for BatchSampler nodes (e.g., --batch-size 32 or --batch-size 38:64,39:128)')
    parser.add_argument('--fixed-seed', type=int, default=None,
                       help='Use fixed random seed for deterministic execution')
    parser.add_argument('--override', type=str, default=None,
                       help='Override specific node configuration values (e.g., --override 56:checkpoint_enabled=True,56:checkpoint_trigger_type=end)')
    args = parser.parse_args()
    
    # Convert node-specific arguments that should be integers when no ':' present
    for arg_name in ['epochs', 'max_iterations', 'batch_size']:
        value = getattr(args, arg_name.replace('-', '_'), None)
        if value and ':' not in value:
            try:
                setattr(args, arg_name.replace('-', '_'), int(value))
            except ValueError:
                pass  # Keep as string if conversion fails
    
    # Convert learning_rate if no ':' present
    if args.learning_rate and ':' not in args.learning_rate:
        try:
            args.learning_rate = float(args.learning_rate)
        except ValueError:
            pass  # Keep as string if conversion fails

    # Parse timeout if provided
    duration_seconds = None
    if args.timeout:
        # First try to parse as a plain number (seconds)
        try:
            duration_seconds = float(args.timeout)
            # Format the display string
            if duration_seconds >= 60:
                display_time = f"{{duration_seconds/60:.1f}}m"
            else:
                display_time = f"{{duration_seconds:.0f}}s"
            print(f"⏱️  Running for {{display_time}} ({{duration_seconds:.0f}} seconds)")
        except ValueError:
            # Not a plain number, try parsing as time format
            try:
                from framework import CheckpointManager
                manager = CheckpointManager("temp")
                duration_seconds = manager.parse_time_format(args.timeout)
                print(f"⏱️  Running for {{args.timeout}} ({{duration_seconds:.0f}} seconds)")
            except Exception as e:
                print(f"⚠️  Invalid timeout format: {{e}}")
                print("   Use formats like: 5, 30s, 5m, 1h30m")
                import sys
                sys.exit(1)

    # Initialize Global configuration
    from framework.globals import Global as g
    # Determine checkpoint directories
    save_checkpoint_dir = args.out_dir if args.save_checkpoint else None
    load_checkpoint_dir = args.load_checkpoint
    
    # Configure logging BEFORE initializing Global and creating nodes
    configure_logging(args.verbose, args.debug)
    
    g.initialize(
        verbose=args.verbose,  # Pass full string for subsystem support
        debug=args.debug,      # Pass full string for subsystem support
        save_checkpoint_dir=save_checkpoint_dir,
        load_checkpoint_dir=load_checkpoint_dir,
        visual_mode=args.visual,
        headless_mode=args.headless,
        inference_mode=args.inference,
        profiling=args.dnne_profiling,
        fixed_seed=args.fixed_seed
    )

    # Set fixed seed if provided for deterministic execution
    if args.fixed_seed is not None:
        print(f"⚠️  Fixed seed disabled for debugging - IsaacGym torch import order issue")
        # TODO: Fix torch import order for IsaacGym workflows
        # import random
        # import numpy as np
        # import torch
        # seed = args.fixed_seed
        # print(f"🔒 Using fixed seed: {{seed}}")
        # torch.manual_seed(seed)
        # torch.cuda.manual_seed_all(seed)
        # np.random.seed(seed)
        # random.seed(seed)
        # # Enable deterministic algorithms
        # torch.backends.cudnn.deterministic = True
        # torch.backends.cudnn.benchmark = False
        # # Note: use_deterministic_algorithms requires CUBLAS_WORKSPACE_CONFIG env var
        # # which we'll set manually when running comparisons

    print("🚀 Starting DNNE Queue-Based Execution")
    if args.inference:
        print("🔍 Inference mode enabled - no training or gradients")
    if args.dnne_profiling:
        print("⏱️  DNNE profiling enabled - timing C++ operations")
    if args.debug:
        if args.debug == 'all':
            print("🔍 Debug mode enabled - showing detailed diagnostic information")
        else:
            print(f"🔍 Debug mode enabled for subsystems: {{args.debug}}")
    elif args.verbose:
        if args.verbose == 'all':
            print("📝 Verbose mode enabled - showing batch-level progress")
        else:
            print(f"📝 Verbose mode enabled for subsystems: {{args.verbose}}")
    else:
        print("📊 Quiet mode - showing epoch summaries only")
    if save_checkpoint_dir:
        print(f"💾 Checkpoint saving enabled, output directory: {{save_checkpoint_dir}}")
    if load_checkpoint_dir:
        print(f"📁 Loading checkpoints from: {{load_checkpoint_dir}}")
    print("=" * 60)

    # Node type mapping for command-line switches
    SWITCH_TO_NODE_TYPE = {{
        'epochs': 'EpochTrackerNode',
        'max_iterations': 'PPOAgentNode',  
        'learning_rate': 'SGDOptimizerNode',
        'batch_size': 'BatchSamplerNode',
    }}

    # Process node-specific arguments
    def process_node_args(args, workflow_nodes):
        '''Process command-line args and assign to specific nodes'''
        node_configs = {{}}
        errors = []
        
        # Map of node types to their IDs from workflow
        node_type_map = {{}}
        for node_id, node_info in workflow_nodes.items():
            node_type = node_info['type']
            if node_type not in node_type_map:
                node_type_map[node_type] = []
            node_type_map[node_type].append(node_id)
        
        # Process each switch
        for switch_name, node_type in SWITCH_TO_NODE_TYPE.items():
            arg_value = getattr(args, switch_name, None)
            if arg_value is None:
                continue
            
            # Find target nodes
            target_nodes = node_type_map.get(node_type, [])
            
            if isinstance(arg_value, str) and ':' in str(arg_value):
                # Parse node-specific values like '30:10,56:5'
                for pair in str(arg_value).split(','):
                    try:
                        node_id, value = pair.strip().split(':')
                        # Convert value to appropriate type
                        if switch_name in ['epochs', 'max_iterations', 'batch_size']:
                            value = int(value)
                        elif switch_name in ['learning_rate']:
                            value = float(value)
                        node_configs.setdefault(node_id, {{}})[switch_name] = value
                    except ValueError:
                        errors.append(f"Invalid format for --{{switch_name}}: '{{pair.strip()}}' (expected format: node_id:value)")
            else:
                # Single value - check for ambiguity
                if len(target_nodes) > 1:
                    errors.append(f"Ambiguous switch --{{switch_name}}: multiple {{node_type}} nodes found: {{target_nodes}}")
                elif len(target_nodes) == 1:
                    node_id = target_nodes[0]
                    node_configs.setdefault(node_id, {{}})[switch_name] = arg_value
                # If no target nodes, silently ignore (backward compatibility)
        
        if errors:
            print('\n❌ Command-line argument errors:')
            for error in errors:
                print(f'   - {{error}}')
            print('\nUse node_id:value syntax to disambiguate, e.g., --epochs 55:10,56:20')
            sys.exit(1)
        
        return node_configs

    # Define workflow nodes info for argument processing
    workflow_nodes = {{
{WORKFLOW_NODES_INFO}
    }}
    
    # Process node-specific configuration
    node_configs = process_node_args(args, workflow_nodes)
    
    # Process generic overrides
    if args.override:
        override_configs, override_errors = parse_override_args(args.override)
        if override_errors:
            print('\n❌ Override argument errors:')
            for error in override_errors:
                print(f'   - {{error}}')
            print('\nUse --override node_id:param=value syntax')
            sys.exit(1)
        
        # Merge override configs into node_configs
        for node_id, config in override_configs.items():
            if node_id not in node_configs:
                node_configs[node_id] = {{}}
            node_configs[node_id].update(config)
    
    # Apply node-specific configuration BEFORE creating nodes
    for node_id, config in node_configs.items():
        for key, value in config.items():
            g.set_node_config(node_id, key, value)

    # Create nodes (AFTER configuration is set)
{NODE_INSTANCES_SECTION}

    # Create nodes dictionary for runner
    nodes = {{
{NODE_DICTIONARY_SECTION}
    }}
    
    # Create runner
    runner = GraphRunner()

    # Add nodes to runner
{ADD_NODES_TO_RUNNER_SECTION}

    # Wire connections
    connections = [
{CONNECTIONS_SECTION}
    ]
    runner.wire_nodes(connections)

    # Run the graph
    try:
        if duration_seconds is not None:
            # Run for specified timeout duration
            import time
            start_time = time.time()
            await runner.run(duration=duration_seconds)
            end_time = time.time()
            print(f'✅ Completed {{args.timeout}} run in {{end_time - start_time:.1f}} seconds')
        else:
            # Run indefinitely (Ctrl+C to stop)
            await runner.run()
    except KeyboardInterrupt:
        print('\n🛑 Stopped by user')

    # Show final statistics
    print('\n📊 Final Statistics:')
    stats = runner.get_stats()
    for node_id, node_stats in stats.items():
        print(f'  {{node_id}}: {{node_stats["compute_count"]}} computations, '
              f'avg time: {{node_stats["last_compute_time"]:.3f}}s')
    
    # Display yield statistics (force print for final report)
    from framework import Global
    Global.print_concurrency_report(force_print=True)

    # Cleanup phase - handle "end" trigger checkpoints and profiling
    print('\n🧹 Running cleanup...')
    for node_id, node in runner.nodes.items():
        # Check if node has checkpoint_manager and "end" trigger type
        if hasattr(node, 'checkpoint_manager') and hasattr(node, 'checkpoint_trigger_type'):
            if node.checkpoint_trigger_type == 'end' and node.checkpoint_manager:
                print(f'💾 Saving end-of-run checkpoint for node {{node_id}}...')
                # Call the node's checkpoint save method directly
                if hasattr(node, 'save_checkpoint'):
                    metadata = {{
                        'reason': 'end_of_run',
                        'final_checkpoint': True
                    }}
                    node.save_checkpoint(trigger_type='external', metadata=metadata)
        
        # Call cleanup if available (for profiling and other cleanup tasks)
        if hasattr(node, 'cleanup'):
            node.cleanup()

if __name__ == '__main__':
    asyncio.run(main())