#!/usr/bin/env python3
"""
Generated by DNNE - Main Entry Point
Metadata: None
"""

import sys
import argparse
from pathlib import Path

# Add current directory to Python path for imports
sys.path.insert(0, str(Path(__file__).parent))

import asyncio
import logging

# Import other required nodes
from nodes.networknode_56 import NetworkNode_56
from nodes.mnistdatasetnode_37 import MNISTDatasetNode_37
from nodes.batchsamplernode_38 import BatchSamplerNode_38
from nodes.getbatchnode_50 import GetBatchNode_50
from nodes.epochtrackernode_55 import EpochTrackerNode_55
from nodes.lossnode_51 import LossNode_51
from nodes.sgdoptimizernode_44 import SGDOptimizerNode_44
from nodes.trainingstepnode_45 import TrainingStepNode_45

from framework.base import GraphRunner
# NOTE: Removed 'from nodes import *' - caused double Isaac Gym initialization
# All required nodes are imported explicitly above

def configure_logging(verbose=False):
    """Configure logging based on verbose flag"""
    if verbose:
        logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(message)s')
    else:
        # Only show WARNING and above for quiet mode
        logging.basicConfig(level=logging.WARNING, format='%(asctime)s - %(name)s - %(message)s')

async def main():
    """Main execution function"""
    # Parse command line arguments
    parser = argparse.ArgumentParser(description='DNNE Generated Training')
    parser.add_argument('--verbose', '-v', action='store_true',
                       help='Enable verbose batch-level logging')
    parser.add_argument('--test-mode', action='store_true',
                       help='Run in test mode with limited duration and performance tracking')
    parser.add_argument('--save-checkpoint-dir', type=str,
                       help='Directory to save checkpoints (will create node_<id> subdirectories)')
    parser.add_argument('--load-checkpoint-dir', type=str,
                       help='Directory to load checkpoints from (expects node_<id> subdirectories)')
    parser.add_argument('--timeout', type=str,
                       help='Training duration (e.g., "5m", "30s", "1h30m")')
    parser.add_argument('--visual', action='store_true',
                       help='Enable visual mode (overrides headless setting)')
    parser.add_argument('--headless', action='store_true',
                       help='Force headless mode (default)')
    parser.add_argument('--inference', action='store_true',
                       help='Run in inference mode (no training, no gradients)')
    parser.add_argument('--dnne-profiling', action='store_true',
                       help='Enable profiling for C++ operations (Isaac Gym)')
    parser.add_argument('--epochs', type=int, default=None,
                       help='Override max epochs for training (overrides workflow setting)')
    args = parser.parse_args()

    # Parse timeout if provided
    duration_seconds = None
    if args.timeout:
        try:
            from run_utils import CheckpointManager
            manager = CheckpointManager("temp")
            duration_seconds = manager.parse_time_format(args.timeout)
            print(f"⏱️  Running for {args.timeout} ({duration_seconds:.0f} seconds)")
        except Exception as e:
            print(f"⚠️  Invalid timeout format: {e}")
            print("   Use formats like: 5m, 30s, 1h30m")
            import sys
            sys.exit(1)

    # Set global flags for nodes to access
    import builtins
    builtins.VERBOSE = args.verbose
    builtins.SAVE_CHECKPOINT_DIR = args.save_checkpoint_dir
    builtins.LOAD_CHECKPOINT_DIR = args.load_checkpoint_dir
    builtins.VISUAL_MODE = args.visual
    builtins.HEADLESS_MODE = args.headless
    builtins.INFERENCE_MODE = args.inference
    builtins.DNNE_PROFILING = args.dnne_profiling
    builtins.EPOCHS_OVERRIDE = args.epochs
    configure_logging(args.verbose)

    print("🚀 Starting DNNE Queue-Based Execution")
    if args.epochs:
        print(f"📊 Epochs override: {args.epochs}")
    if args.inference:
        print("🔍 Inference mode enabled - no training or gradients")
    if args.dnne_profiling:
        print("⏱️  DNNE profiling enabled - timing C++ operations")
    if args.verbose:
        print("📝 Verbose mode enabled - showing all batch details")
    else:
        print("📊 Quiet mode - showing epoch summaries only")
    if args.save_checkpoint_dir:
        print(f"💾 Checkpoint saving to: {args.save_checkpoint_dir}")
    if args.load_checkpoint_dir:
        print(f"📁 Loading checkpoints from: {args.load_checkpoint_dir}")
    print("=" * 60)

    # Create nodes
    node_56 = NetworkNode_56("56")
    node_37 = MNISTDatasetNode_37("37")
    node_38 = BatchSamplerNode_38("38")
    node_50 = GetBatchNode_50("50")
    node_55 = EpochTrackerNode_55("55")
    node_51 = LossNode_51("51")
    node_44 = SGDOptimizerNode_44("44")
    node_45 = TrainingStepNode_45("45")

    # Create runner
    runner = GraphRunner()

    # Add nodes to runner
    runner.add_node(node_56)
    runner.add_node(node_37)
    runner.add_node(node_38)
    runner.add_node(node_50)
    runner.add_node(node_55)
    runner.add_node(node_51)
    runner.add_node(node_44)
    runner.add_node(node_45)

    # Wire connections
    connections = [
        ("37", "dataset", "38", "dataset"),
        ("37", "schema", "38", "schema"),
        ("44", "optimizer", "45", "optimizer"),
        ("38", "dataloader", "50", "dataloader"),
        ("38", "schema", "50", "schema"),
        ("51", "loss", "45", "loss"),
        ("50", "labels", "51", "labels"),
        ("50", "epoch_stats", "55", "epoch_stats"),
        ("51", "loss", "55", "loss"),
        ("51", "accuracy", "55", "accuracy"),
        ("45", "ready", "50", "trigger"),
        ("56", "model", "44", "network"),
        ("56", "output", "51", "predictions"),
        ("50", "images", "56", "input"),
    ]
    runner.wire_nodes(connections)

    # Run the graph
    try:
        if args.test_mode:
            print('🧪 Test mode: Running for 30 seconds with performance tracking')
            import time
            start_time = time.time()
            await runner.run(duration=30.0)  # Run for 30 seconds in test mode
            end_time = time.time()
            print(f'✅ Test mode completed in {end_time - start_time:.1f} seconds')
        elif duration_seconds is not None:
            # Run for specified timeout duration
            import time
            start_time = time.time()
            await runner.run(duration=duration_seconds)
            end_time = time.time()
            print(f'✅ Completed {args.timeout} run in {end_time - start_time:.1f} seconds')
        else:
            # Run indefinitely (Ctrl+C to stop)
            await runner.run()
    except KeyboardInterrupt:
        print('\n🛑 Stopped by user')

    # Show final statistics
    print('\n📊 Final Statistics:')
    stats = runner.get_stats()
    for node_id, node_stats in stats.items():
        print(f'  {node_id}: {node_stats["compute_count"]} computations, '
              f'avg time: {node_stats["last_compute_time"]:.3f}s')

    # Save timing data if profiling was enabled
    if args.dnne_profiling:
        print('\n⏱️  Saving DNNE profiling data...')
        # Call cleanup on all nodes (environment nodes will save timing data)
        for node in runner.nodes.values():
            if hasattr(node, 'cleanup'):
                node.cleanup()


if __name__ == '__main__':
    asyncio.run(main())