#!/usr/bin/env python3
"""
Generated by DNNE - Main Entry Point
Metadata: None
"""

import sys
import os
import argparse
from pathlib import Path

# Add current directory to Python path for imports
sys.path.insert(0, str(Path(__file__).parent))

# Configure paths using DNNE configuration system
try:
    # Try to import configuration module
    from dnne_config import DNNEConfig
    config = DNNEConfig()
    
    # Add paths from configuration
    isaac_gym_path = config.get('paths.isaac_gym')
    isaac_gym_envs_path = config.get('paths.isaac_gym_envs')
    linux_support_path = config.get('paths.linux_support')
    rl_games_path = config.get('paths.rl_games_dnne')
    
    if isaac_gym_path:
        sys.path.append(os.path.join(isaac_gym_path, "python"))
    if linux_support_path:
        sys.path.append(linux_support_path)
    if isaac_gym_envs_path:
        sys.path.append(isaac_gym_envs_path)
    if rl_games_path:
        sys.path.append(rl_games_path)
    
    print(f"Using paths from configuration: isaac_gym={isaac_gym_path}")
    
except ImportError:
    # Fallback to environment variables or defaults if config not available
    isaac_gym_path = os.environ.get('DNNE_ISAAC_GYM', "/home/asantanna/DNNE-LINUX-SUPPORT/isaacgym")
    isaac_gym_envs_path = os.environ.get('DNNE_ISAAC_GYM_ENVS', "/home/asantanna/DNNE-LINUX-SUPPORT/IsaacGymEnvs")
    linux_support_path = os.environ.get('DNNE_LINUX_SUPPORT', "/home/asantanna/DNNE-LINUX-SUPPORT")
    rl_games_path = os.environ.get('DNNE_RL_GAMES', "/home/asantanna/DNNE-LINUX-SUPPORT/rl_games_dnne")
    
    sys.path.append(os.path.join(isaac_gym_path, "python"))
    sys.path.append(linux_support_path)
    sys.path.append(isaac_gym_envs_path)
    if rl_games_path and os.path.exists(rl_games_path):
        sys.path.append(rl_games_path)
    
    print(f"Using paths from environment/defaults: isaac_gym={isaac_gym_path}")

import asyncio
import logging

# Import other required nodes
from nodes.ppoagentnode_8 import PPOAgentNode_8

from framework import GraphRunner
# NOTE: Removed 'from nodes import *' - caused double Isaac Gym initialization
# All required nodes are imported explicitly above

def configure_logging(verbose=False):
    """Configure logging based on verbose flag"""
    if verbose:
        logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(message)s')
    else:
        # Only show WARNING and above for quiet mode
        logging.basicConfig(level=logging.WARNING, format='%(asctime)s - %(name)s - %(message)s')

async def main():
    """Main execution function"""
    # Parse command line arguments
    parser = argparse.ArgumentParser(description='DNNE Generated Training')
    parser.add_argument('--verbose', '-v', action='store_true',
                       help='Enable verbose batch-level logging')
    parser.add_argument('--test-mode', action='store_true',
                       help='Run in test mode with limited duration and performance tracking')
    parser.add_argument('--save-checkpoint-dir', type=str,
                       help='Directory to save checkpoints (will create node_<id> subdirectories)')
    parser.add_argument('--load-checkpoint-dir', type=str,
                       help='Directory to load checkpoints from (expects node_<id> subdirectories)')
    parser.add_argument('--timeout', type=str,
                       help='Training duration (e.g., "5m", "30s", "1h30m")')
    parser.add_argument('--visual', action='store_true',
                       help='Enable visual mode (overrides headless setting)')
    parser.add_argument('--headless', action='store_true',
                       help='Force headless mode (default)')
    parser.add_argument('--inference', action='store_true',
                       help='Run in inference mode (no training, no gradients)')
    parser.add_argument('--dnne-profiling', action='store_true',
                       help='Enable profiling for C++ operations (Isaac Gym)')
    parser.add_argument('--epochs', type=int, default=None,
                       help='Override max epochs for training (overrides workflow setting)')
    parser.add_argument('--fixed-seed', type=int, default=None,
                       help='Use fixed random seed for deterministic execution')
    args = parser.parse_args()

    # Parse timeout if provided
    duration_seconds = None
    if args.timeout:
        try:
            from framework import CheckpointManager
            manager = CheckpointManager("temp")
            duration_seconds = manager.parse_time_format(args.timeout)
            print(f"⏱️  Running for {args.timeout} ({duration_seconds:.0f} seconds)")
        except Exception as e:
            print(f"⚠️  Invalid timeout format: {e}")
            print("   Use formats like: 5m, 30s, 1h30m")
            import sys
            sys.exit(1)

    # Set global flags for nodes to access
    import builtins
    builtins.VERBOSE = args.verbose
    builtins.SAVE_CHECKPOINT_DIR = args.save_checkpoint_dir
    builtins.LOAD_CHECKPOINT_DIR = args.load_checkpoint_dir
    builtins.VISUAL_MODE = args.visual
    builtins.HEADLESS_MODE = args.headless
    builtins.INFERENCE_MODE = args.inference
    builtins.DNNE_PROFILING = args.dnne_profiling
    builtins.EPOCHS_OVERRIDE = args.epochs
    builtins.FIXED_SEED = args.fixed_seed
    configure_logging(args.verbose)

    # Set fixed seed if provided for deterministic execution
    if args.fixed_seed is not None:
        print(f"⚠️  Fixed seed disabled for debugging - IsaacGym torch import order issue")
        # TODO: Fix torch import order for IsaacGym workflows
        # import random
        # import numpy as np
        # import torch
        # seed = args.fixed_seed
        # print(f"🔒 Using fixed seed: {seed}")
        # torch.manual_seed(seed)
        # torch.cuda.manual_seed_all(seed)
        # np.random.seed(seed)
        # random.seed(seed)
        # # Enable deterministic algorithms
        # torch.backends.cudnn.deterministic = True
        # torch.backends.cudnn.benchmark = False
        # # Note: use_deterministic_algorithms requires CUBLAS_WORKSPACE_CONFIG env var
        # # which we'll set manually when running comparisons

    print("🚀 Starting DNNE Queue-Based Execution")
    if args.epochs:
        print(f"📊 Epochs override: {args.epochs}")
    if args.inference:
        print("🔍 Inference mode enabled - no training or gradients")
    if args.dnne_profiling:
        print("⏱️  DNNE profiling enabled - timing C++ operations")
    if args.verbose:
        print("📝 Verbose mode enabled - showing all batch details")
    else:
        print("📊 Quiet mode - showing epoch summaries only")
    if args.save_checkpoint_dir:
        print(f"💾 Checkpoint saving to: {args.save_checkpoint_dir}")
    if args.load_checkpoint_dir:
        print(f"📁 Loading checkpoints from: {args.load_checkpoint_dir}")
    print("=" * 60)

    # Create nodes
    node_8 = PPOAgentNode_8("8")

    # Create runner
    runner = GraphRunner()

    # Add nodes to runner
    runner.add_node(node_8)

    # Wire connections
    connections = [
    ]
    runner.wire_nodes(connections)

    # Run the graph
    try:
        if args.test_mode:
            print('🧪 Test mode: Running for 30 seconds with performance tracking')
            import time
            start_time = time.time()
            await runner.run(duration=30.0)  # Run for 30 seconds in test mode
            end_time = time.time()
            print(f'✅ Test mode completed in {end_time - start_time:.1f} seconds')
        elif duration_seconds is not None:
            # Run for specified timeout duration
            import time
            start_time = time.time()
            await runner.run(duration=duration_seconds)
            end_time = time.time()
            print(f'✅ Completed {args.timeout} run in {end_time - start_time:.1f} seconds')
        else:
            # Run indefinitely (Ctrl+C to stop)
            await runner.run()
    except KeyboardInterrupt:
        print('\n🛑 Stopped by user')

    # Show final statistics
    print('\n📊 Final Statistics:')
    stats = runner.get_stats()
    for node_id, node_stats in stats.items():
        print(f'  {node_id}: {node_stats["compute_count"]} computations, '
              f'avg time: {node_stats["last_compute_time"]:.3f}s')

    # Save timing data if profiling was enabled
    if args.dnne_profiling:
        print('\n⏱️  Saving DNNE profiling data...')
        # Call cleanup on all nodes (environment nodes will save timing data)
        for node in runner.nodes.values():
            if hasattr(node, 'cleanup'):
                node.cleanup()


if __name__ == '__main__':
    asyncio.run(main())