#!/usr/bin/env python3
"""
Generated by DNNE - Main Entry Point
Metadata: None
"""

# CRITICAL: Import isaacgym before ANY other imports to prevent torch import order issues
# This MUST be the first import after the header comments
import isaacgym

import sys
import argparse
from pathlib import Path

# Add current directory to Python path for imports
sys.path.insert(0, str(Path(__file__).parent))

import asyncio
import logging

# CRITICAL: Import Isaac Gym nodes directly (not via __init__.py) to prevent torch import order issues
# This prevents 'PyTorch was imported before isaacgym' error
from nodes.isaacgymstepnode_9 import IsaacGymStepNode_9
from nodes.isaacgymenvnode_7 import IsaacGymEnvNode_7

# Import other required nodes
from nodes.ppotrainernode_6 import PPOTrainerNode_6
from nodes.ornode_2 import ORNode_2
from nodes.ppoagentnode_3 import PPOAgentNode_3
from nodes.cartpoleactionnode_11 import CartpoleActionNode_11

from framework.base import GraphRunner
# NOTE: Removed 'from nodes import *' - caused double Isaac Gym initialization
# All required nodes are imported explicitly above

def configure_logging(verbose=False):
    """Configure logging based on verbose flag"""
    if verbose:
        logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(message)s')
    else:
        # Only show WARNING and above for quiet mode
        logging.basicConfig(level=logging.WARNING, format='%(asctime)s - %(name)s - %(message)s')

async def main():
    """Main execution function"""
    # Parse command line arguments
    parser = argparse.ArgumentParser(description='DNNE Generated Training')
    parser.add_argument('--verbose', '-v', action='store_true',
                       help='Enable verbose batch-level logging')
    parser.add_argument('--test-mode', action='store_true',
                       help='Run in test mode with limited duration and performance tracking')
    parser.add_argument('--save-checkpoint-dir', type=str,
                       help='Directory to save checkpoints (will create node_<id> subdirectories)')
    parser.add_argument('--load-checkpoint-dir', type=str,
                       help='Directory to load checkpoints from (expects node_<id> subdirectories)')
    parser.add_argument('--timeout', type=str,
                       help='Training duration (e.g., "5m", "30s", "1h30m")')
    parser.add_argument('--visual', action='store_true',
                       help='Enable visual mode (overrides headless setting)')
    parser.add_argument('--headless', action='store_true',
                       help='Force headless mode (default)')
    parser.add_argument('--inference', action='store_true',
                       help='Run in inference mode (no training, no gradients)')
    parser.add_argument('--dnne-profiling', action='store_true',
                       help='Enable profiling for C++ operations (Isaac Gym)')
    args = parser.parse_args()

    # Parse timeout if provided
    duration_seconds = None
    if args.timeout:
        try:
            from run_utils import CheckpointManager
            manager = CheckpointManager("temp")
            duration_seconds = manager.parse_time_format(args.timeout)
            print(f"⏱️  Running for {args.timeout} ({duration_seconds:.0f} seconds)")
        except Exception as e:
            print(f"⚠️  Invalid timeout format: {e}")
            print("   Use formats like: 5m, 30s, 1h30m")
            import sys
            sys.exit(1)

    # Set global flags for nodes to access
    import builtins
    builtins.VERBOSE = args.verbose
    builtins.SAVE_CHECKPOINT_DIR = args.save_checkpoint_dir
    builtins.LOAD_CHECKPOINT_DIR = args.load_checkpoint_dir
    builtins.VISUAL_MODE = args.visual
    builtins.HEADLESS_MODE = args.headless
    builtins.INFERENCE_MODE = args.inference
    builtins.DNNE_PROFILING = args.dnne_profiling
    configure_logging(args.verbose)

    print("🚀 Starting DNNE Queue-Based Execution")
    if args.inference:
        print("🔍 Inference mode enabled - no training or gradients")
    if args.dnne_profiling:
        print("⏱️  DNNE profiling enabled - timing C++ operations")
    if args.verbose:
        print("📝 Verbose mode enabled - showing all batch details")
    else:
        print("📊 Quiet mode - showing epoch summaries only")
    if args.save_checkpoint_dir:
        print(f"💾 Checkpoint saving to: {args.save_checkpoint_dir}")
    if args.load_checkpoint_dir:
        print(f"📁 Loading checkpoints from: {args.load_checkpoint_dir}")
    print("=" * 60)

    # Create nodes
    node_6 = PPOTrainerNode_6("6")
    node_9 = IsaacGymStepNode_9("9")
    node_2 = ORNode_2("2")
    node_3 = PPOAgentNode_3("3")
    node_11 = CartpoleActionNode_11("11")
    node_7 = IsaacGymEnvNode_7("7")

    # Create runner
    runner = GraphRunner()

    # Add nodes to runner
    runner.add_node(node_6)
    runner.add_node(node_9)
    runner.add_node(node_2)
    runner.add_node(node_3)
    runner.add_node(node_11)
    runner.add_node(node_7)

    # Wire connections
    connections = [
        ("2", "output", "3", "observations"),
        ("3", "policy_output", "6", "policy_output"),
        ("3", "model", "6", "model"),
        ("7", "observations", "2", "input_a"),
        ("7", "sim_handle", "9", "sim_handle"),
        ("9", "observations", "6", "state"),
        ("9", "observations", "2", "input_b"),
        ("6", "training_complete", "9", "trigger"),
        ("9", "rewards", "6", "reward"),
        ("9", "done", "6", "done"),
        ("11", "action", "9", "actions"),
        ("3", "policy_output", "11", "policy"),
    ]
    runner.wire_nodes(connections)

    # Run the graph
    try:
        if args.test_mode:
            print('🧪 Test mode: Running for 30 seconds with performance tracking')
            import time
            start_time = time.time()
            await runner.run(duration=30.0)  # Run for 30 seconds in test mode
            end_time = time.time()
            print(f'✅ Test mode completed in {end_time - start_time:.1f} seconds')
        elif duration_seconds is not None:
            # Run for specified timeout duration
            import time
            start_time = time.time()
            await runner.run(duration=duration_seconds)
            end_time = time.time()
            print(f'✅ Completed {args.timeout} run in {end_time - start_time:.1f} seconds')
        else:
            # Run indefinitely (Ctrl+C to stop)
            await runner.run()
    except KeyboardInterrupt:
        print('\n🛑 Stopped by user')

    # Show final statistics
    print('\n📊 Final Statistics:')
    stats = runner.get_stats()
    for node_id, node_stats in stats.items():
        print(f'  {node_id}: {node_stats["compute_count"]} computations, '
              f'avg time: {node_stats["last_compute_time"]:.3f}s')

    # Save timing data if profiling was enabled
    if args.dnne_profiling:
        print('\n⏱️  Saving DNNE profiling data...')
        # Call cleanup on all nodes (environment nodes will save timing data)
        for node in runner.nodes.values():
            if hasattr(node, 'cleanup'):
                node.cleanup()


if __name__ == '__main__':
    asyncio.run(main())