#!/usr/bin/env python3
"""
Generated by DNNE Export System
Workflow: {WORKFLOW_NAME}
Generated at: {TIMESTAMP}
Description: {DESCRIPTION}
"""

import asyncio
import logging
import sys
import os
from pathlib import Path

# Add paths for isaacgym
sys.path.append("/home/asantanna/DNNE-LINUX-SUPPORT/isaacgym/python")
sys.path.append("/home/asantanna/DNNE-LINUX-SUPPORT")
sys.path.append("/home/asantanna/DNNE-LINUX-SUPPORT/IsaacGymEnvs")

# Isaac Gym must be imported before torch
import isaacgym

# Now import other dependencies
import torch
import torch.nn as nn
import numpy as np
from typing import Dict, List, Any, Optional

# Import framework components
from framework import GraphRunner, QueueNode, SensorNode, TrainingCompleteException

# Import node implementations
{NODE_IMPORTS}

# Generated node classes
{NODE_CLASSES}

async def main():
    """Main execution function for the exported workflow"""
    # Configure logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(message)s'
    )
    
    # Create workflow nodes
    nodes = {
{NODE_INSTANCES}
    }
    
    # Define connections
    connections = [
{CONNECTIONS}
    ]
    
    # Create and run the graph
    runner = GraphRunner(nodes, connections)
    await runner.run()

if __name__ == "__main__":
    # Run the async main function
    asyncio.run(main())