#!/usr/bin/env python3
"""
Script to help convert RETURN_TYPES/RETURN_NAMES to OUTPUT_DICT format
"""

import re
import sys
from pathlib import Path
from typing import Optional, Tuple, List

def parse_return_info(file_content: str) -> Optional[Tuple[List[str], List[str]]]:
    """Extract RETURN_TYPES and RETURN_NAMES from file content"""
    
    # Find RETURN_TYPES
    types_match = re.search(r'RETURN_TYPES\s*=\s*\((.*?)\)', file_content, re.DOTALL)
    if not types_match:
        return None
    
    types_str = types_match.group(1).strip()
    if not types_str:
        return None
    
    # Parse types (handle both simple strings and quoted strings)
    types = []
    for item in re.findall(r'"[^"]+"|\'[^\']+\'|[^,\s]+', types_str):
        item = item.strip().strip(',').strip()
        if item:
            types.append(item)
    
    # Find RETURN_NAMES
    names_match = re.search(r'RETURN_NAMES\s*=\s*\((.*?)\)', file_content, re.DOTALL)
    if not names_match:
        # Use types as names if RETURN_NAMES not found
        names = [t.strip('"\'').lower() for t in types]
    else:
        names_str = names_match.group(1).strip()
        names = []
        for item in re.findall(r'"[^"]+"|\'[^\']+\'|[^,\s]+', names_str):
            item = item.strip().strip(',').strip()
            if item:
                names.append(item)
    
    return types, names

def generate_output_dict(types: List[str], names: List[str]) -> str:
    """Generate OUTPUT_DICT definition"""
    lines = ["    OUTPUT_DICT = {"]
    
    for i, (type_val, name_val) in enumerate(zip(types, names)):
        # Remove quotes from values
        type_val = type_val.strip('"\'')
        name_val = name_val.strip('"\'')
        
        # Build the dictionary entry
        entry = f'        {i}: {{"type": "{type_val}", "name": "{name_val}"}}'
        
        # Add comma except for last entry
        if i < len(types) - 1:
            entry += ","
        
        lines.append(entry)
    
    lines.append("    }")
    lines.append("    # RETURN_TYPES and RETURN_NAMES auto-generated by OutputDictMixin")
    
    return "\n".join(lines)

def process_file(filepath: Path) -> bool:
    """Process a single file"""
    content = filepath.read_text()
    
    # Skip if already has OUTPUT_DICT
    if "OUTPUT_DICT" in content:
        print(f"  Skipping {filepath.name} - already has OUTPUT_DICT")
        return False
    
    # Parse return info
    result = parse_return_info(content)
    if not result:
        print(f"  Skipping {filepath.name} - no RETURN_TYPES found")
        return False
    
    types, names = result
    
    # Generate OUTPUT_DICT
    output_dict_str = generate_output_dict(types, names)
    
    # Replace the RETURN_TYPES and RETURN_NAMES lines with OUTPUT_DICT
    # Find RETURN_TYPES line
    types_pattern = r'(\s*)RETURN_TYPES\s*=\s*\([^)]*\)'
    names_pattern = r'(\s*)RETURN_NAMES\s*=\s*\([^)]*\)'
    
    # First replace RETURN_TYPES with OUTPUT_DICT
    new_content = re.sub(types_pattern, output_dict_str, content, count=1)
    
    # Then remove RETURN_NAMES line (it follows RETURN_TYPES)
    new_content = re.sub(names_pattern, '', new_content, count=1)
    
    # Clean up any double newlines
    new_content = re.sub(r'\n\n\n+', '\n\n', new_content)
    
    print(f"  Converted {filepath.name}")
    print(f"    Types: {types}")
    print(f"    Names: {names}")
    
    # Write back
    filepath.write_text(new_content)
    return True

def main():
    """Main conversion script"""
    
    # Find all visnode files
    visnode_dir = Path("/home/asantanna/DNNE/DNNE-UI/custom_nodes")
    visnode_files = list(visnode_dir.glob("*_visnode.py"))
    
    print(f"Found {len(visnode_files)} visnode files")
    print()
    
    converted_count = 0
    for filepath in sorted(visnode_files):
        if process_file(filepath):
            converted_count += 1
    
    print()
    print(f"Converted {converted_count} files to OUTPUT_DICT format")
    
    # List files that may need virtual marking
    print()
    print("Files that may need virtual outputs marked:")
    print("  - network_visnode.py: model output (virtual)")
    print("  - isaac_gym_envs_visnode.py: env output (virtual)")
    print()
    print("Files that may need virtual inputs marked:")
    print("  - sgd_optimizer_visnode.py: model input (virtual)")
    print("  - training_step_visnode.py: optimizer input (virtual)")
    print("  - ppo_agent_visnode.py: env_config input (virtual)")
    print("  - isaac_gym_sim_visnode.py: env_config input (virtual)")

if __name__ == "__main__":
    main()